Hudson private security realm implementation
divyasivasamy/jenkins pull request #1
Opened 2023-08-04 10:15 UTC by divyasivasamy

See [JENKINS-XXXXX](https://issues.jenkins.io/browse/JENKINS-XXXXX).

### Testing done

### Proposed changelog entries

- Entry 1: Issue, human-readable text
- […]

### Proposed upgrade guidelines

N/A

```[tasklist]
### Submitter checklist
- [ ] The Jira issue, if it exists, is well-described.
- [ ] The changelog entries and upgrade guidelines are appropriate for the audience affected by the change (users or developers, depending on the change) and are in the imperative mood (see [examples](https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/weekly.yml)). Fill in the **Proposed upgrade guidelines** section only if there are breaking changes or changes that may require extra steps from users during upgrade.
- [ ] There is automated testing or an explanation as to why this change has no tests.
- [ ] New public classes, fields, and methods are annotated with `@Restricted` or have `@since TODO` Javadocs, as appropriate.
- [ ] New deprecations are annotated with `@Deprecated(since = "TODO")` or `@Deprecated(forRemoval = true, since = "TODO")`, if applicable.
- [ ] New or substantially changed JavaScript is not defined inline and does not call `eval` to ease future introduction of Content Security Policy (CSP) directives (see [documentation](https://www.jenkins.io/doc/developer/security/csp/)).
- [ ] For dependency updates, there are links to external changelogs and, if possible, full differentials.
- [ ] For new APIs and extension points, there is a link to at least one consumer.
```

### Desired reviewers

@mention

Before the changes are marked as `ready-for-merge`:

```[tasklist]
### Maintainer checklist
- [ ] There are at least two (2) approvals for the pull request and no outstanding requests for change.
- [ ] Conversations in the pull request are over, or it is explicit that a reviewer is not blocking the change.
- [ ] Changelog entries in the pull request title and/or **Proposed changelog entries** are accurate, human-readable, and in the imperative mood.
- [ ] Proper changelog labels are set so that the changelog can be generated automatically.
- [ ] If the change needs additional upgrade steps from users, the `upgrade-guide-needed` label is set and there is a **Proposed upgrade guidelines** section in the pull request title (see [example](https://github.com/jenkinsci/jenkins/pull/4387)).
- [ ] If it would make sense to backport the change to LTS, a Jira issue must exist, be a _Bug_ or _Improvement_, and be labeled as `lts-candidate` to be considered (see [query](https://issues.jenkins.io/issues/?filter=12146)).
```

2023-08-04 13:40 UTC, jwojciebee commented
@divyasivasamy, can you update PR with more detailed description of the change ?

2023-08-04 14:08 UTC, jwojciebee requested changes

2023-08-04 14:08 UTC, jwojciebee commented on core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
> +        public static final int ITERATION_COUNT = 1000;
To consider if iteration count should be hard coded or moved to the System Properties. Also we should consider storing it the same way it is done in BCrypt https://en.wikipedia.org/wiki/Bcrypt. They are not storing actual iteration count but the power of 2 which is used to get it. So for example value 10 of it, means 2^10 = 1024 iterations.

2023-08-04 14:08 UTC, jwojciebee commented on core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
> +            int iterations = ITERATION_COUNT;
I think variable is unnecessary and constant ITERATION_COUNT can be used directly

2023-08-04 14:08 UTC, jwojciebee commented on test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
> -    @Before
why that code had to be removed?

2023-08-04 14:08 UTC, jwojciebee commented on test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
> +    public void hashedPasswordTestPBKDF2() {
It looks like partially someone tried to follow: [state under test][expected behaviour] unit tests naming convention here in this file. Please try to rename your tests accordingly. In particular word "Test" is not used in other tests names.

2023-08-04 14:08 UTC, jwojciebee commented on test/src/test/java/hudson/security/HudsonPrivateSecurityRealmTest.java
> +        PASSWORD_ENCODER.isPasswordHashed("#pbkdf2:" + PASSWORD_HASH_ENCODER.encode("password"));
why it is not in assertTrue(...) ?

2023-08-07 07:22 UTC, SujathaH reviewed
Ensure all possible cases are tested.
Update the description of PR

2023-08-07 07:22 UTC, SujathaH commented on core/src/main/java/hudson/Util.java
> +      return SystemProperties.getBoolean(Util.class.getName() + GET_FIPS_MODE);
better to log the value, will be helpful during triage.

2023-08-07 07:22 UTC, SujathaH commented on core/src/main/java/hudson/security/HudsonPrivateSecurityRealm.java
> +    /* package */ static final PasswordHashEncoder PASSWORD_HASH_ENCODER =  Util.isFipsMode() ? new PBKDF2PasswordEncoder() : new JBCryptEncoder();
will be useful if we log the encoder being picked up at runtime, will be helpful during triage.

2023-08-17 06:44 UTC, closed without merging